/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20Bridged } from "./ERC20Bridged";
export type { ERC20CrossChain } from "./ERC20CrossChain";
export type { ExampleProxy } from "./ExampleProxy";
export type { IERC20CrossChain } from "./IERC20CrossChain";
