/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as executables from "./executables";
export type { executables };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as upgradables from "./upgradables";
export type { upgradables };
