/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20Bridged__factory } from "./ERC20Bridged__factory";
export { ERC20CrossChain__factory } from "./ERC20CrossChain__factory";
export { ExampleProxy__factory } from "./ExampleProxy__factory";
export { IERC20CrossChain__factory } from "./IERC20CrossChain__factory";
